version: '2.1'
orbs:
  gh: circleci/github-cli@2.0
jobs:
  get-token:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - gh/install
      - run:
          command: >
            if [[ -z "$GITHUB_TOKEN" ]]; then echo "not set"; else echo "set"; fi
            gh api /user
          name: Get Token
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:latest
        environment:
          PROD_DOMAIN: share.ipfs.io
          DEV_DOMAIN: dev.share.ipfs.io
          BUILD_DIR: build
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy website to IPFS
          command: |
            pin_name="ipfs-share-files build $CIRCLE_BUILD_NUMBER"

            hash=$(pin-to-cluster.sh "$pin_name" /tmp/workspace/$BUILD_DIR)

            echo "Website added to IPFS: https://dweb.link/ipfs/$hash"

            # Update DNSlink for prod or dev domain
            if [ "$CIRCLE_BRANCH" == "production" ] ; then
              dnslink-dnsimple -d $PROD_DOMAIN -r _dnslink -l /ipfs/$hash
            fi
            if [ "$CIRCLE_BRANCH" == "main" ] ; then
              dnslink-dnsimple -d $DEV_DOMAIN -r _dnslink -l /ipfs/$hash
            fi

workflows:
  version: '2.1'
  get-token:
    jobs:
      - get-token:
          context: ipfs-dns-deploy
  build-deploy:
    jobs:
      - build
      - deploy:
          context: ipfs-dns-deploy
          requires:
            - build
